### ISSUE TITLE
[consensus] Implement new Random Committee Swapping mechanism

### ISSUE THREAD

**Issue by duyhtq** [incognitochain/incognito-chain#310]
The current committee swapping method is problematic.

1. It creates a lot of unnecessary connections between pending validators and committees - introducing unnecessary overhead to the network.

2. It blocks new candidates from joining the committee, because of the current FIFO design.

The general solution is to:

1.  Reduce the pending candidate pipeline size

2.  Use a weighted random algorithm.  The weight could be either waiting time, or reputation (the number of blocks this validator has produced), or a mutation idea (like freshness or newness of a validator), or a mixture.

@0xmerman  @0xkumi @0xbarmanu  let's discuss it tomorrow in the office and finalize it

**Comment by 0xmerman** [comment]
The general solution should consider these characteristic:
1. Random assignment new validator into shard
2. Consensus Liveliness 
- Data availability for in-coming committee
- Sufficient amount of swap-in and swap-out committee (must < 1/3n)
3. Minimize message throughput and peer connection
Further more, we should consider fairness for user:
- Staking time
- Staking amount

**Comment by 0xmerman** [comment]
After discussion, we would remain the current flow, included:
1. Candidates
2. Pending Validators
3. Committees

For each epoch, we would choose only a subset of candidates, and assign this subset to shard. This approach still satisfies System characteristic and balance the probability for user to get into shard according into staking time (if user stake first, he/she will have a lot of chance to be our validator)

**Comment by duyhtq** [comment]
move from design discussion to implementation by @0xmerman

**Comment by 0xmerman** [comment]
In first implementation, team will make an important modification:
- Limit the number of pending validators list

The work flow now will be:
1. Shuffle candidate list priority with random number. This provide an equal chance for every candidates regardless of staking time (time enter candidate list)
2. Consecutively pick candidate in priority list and use random number to assign this candidate to shard.
a. If shard pending validators list reach limit then this candidate failed to enter (and will go back into candidate list)
b. If shard pending validators list haven't reached its limit yet then candidate will enter successfully

This may not provide absolute equal between candidate, because some shard pending validators list have already full. But in long term performance, team believe that every shard pending validators list has roughly equal length

3. After this assignment, work flow remain the same as our current solution.

@duyhtq please give us some feedback

**Comment by 0xmerman** [comment]
I have update both code and unit test, also conduct integration and unit test. @thaibao-incognito @0xkumi please review for me at branch dev/new-swap
