### ISSUE TITLE
Incognito Coding Style

### ISSUE THREAD

**Issue by duyhtq** [incognitochain/incognito-chain#318]
as the project grows and we have many team members now, we need to have a common *coding style guideline* to keep the codebase consistent and make the code review process easier.

some references from other large open-source projects:

https://github.com/torvalds/linux/blob/master/Documentation/process/coding-style.rst
https://github.com/bitcoin/bitcoin/blob/master/doc/developer-notes.md
https://golang.org/doc/effective_go.html
https://github.com/golang/go/wiki/CodeReviewComments
https://github.com/ethereum/go-ethereum/wiki/Code-Review-Guidelines

**Comment by 0xmerman** [comment]
Effective go and Code Guidelines by go ethereum provide a lot of rules, so i think our team should limit it to 10 or 15 rule that we really need.

I have some suggestion from Effective Go and Go-ethereum code:
1. Code must be formatting before merge (using manual or automatically fix with gofmt)
2. Comment:
a. Block comment: 
- Comment a package 
- Comment a large amount of code
b. Line comment:
- Comment function usage
- Comment struct usage
- Comment in param and return params
```
// Request represents a request to run a command.
type Request struct { ...

// Encode writes the JSON encoding of req to w.
func Encode(w io.Writer, req *Request) { ...
```
3. Naming:
- Package, function, struct and variable naming should reflect it meaning in our process
* For example When we want to count something, should:
```
var countSomething int
```
- Avoid:
```
var a int
```
- Exported value or function, if the have a mutex to lock resource then this function or value should be lock before processing
4. Function Length
- Function should not exceed 150 lines.
- Each function should contains enough logic and line so it can be easily read and test
5. Control Structure, If
- Code must guard against a sequence of error conditions, example:
```f, err := os.Open(name)
if err != nil {
    return err
}
d, err := f.Stat()
if err != nil {
    f.Close()
    return err
}
codeUsing(f, d)```
6. Method Pointer and Value
- Setter or any function that can change value of struct/type should have pointer receiver
```
func (blockchain *Blockchain) SetSomething(){//...}
```
- Getter or any function that never intend to change value of struct/type should have value receiver
```
func (point Point) GetSomething(){//...}
```
7. Return Pointer and Value
- Big struct variable should be return as pointer
- Small struct or value should be return as value
8. Log
- Log should print: message and value of variable
9. Error
- All Error must be warp with: 
+ Key
+ Expected value
+ Real value
Example:
```
NewBlockchainError(InstructionHash, fmt.Errorf("Expected Instruct Hash to be %+v but get %+v", block.Header.InstructionHash, tempInstructionHash)
```
10. Mutex
- Resource that guard by mutex, should be use internal and carefully
11. All constant must be declared in constant.go
12. Channel and goroutine
- Goroutine: make sure sub-goroutine should be terminate (or it will consume our resource)
- If some value wish to be transfer from one goroutine to many goroutine, we should use internal pubsub instead of a lot of channel

Team please feedback for a great and simple code guideline
