### ISSUE TITLE
[Spec] What is burning address and What is it?

### ISSUE THREAD

**Issue by thaibao-incognito** [incognitochain/incognito-chain#429]

**Comment by hieu013** [comment]
Deadline: 2 Jan 2020

**Comment by hieu013** [comment]
# Burn Address


* Burn address: is a special address on Incognito chain, which is not accessible by anyone, since no one own the private keys to that address.

* Burned assets (coins or tokens): mean eliminated assets by sending them to a burn address.

* Minted assets (coins or tokens): mean created new assets then distributed them to some address on Incognito chain.

In Incognito chain, we use burn and mint mechanism to archive consensus in some cases such as stake/unstake, deposit/withdraw token in the bridge, and PDex.
  
#### How to generate Burn Address
* The formula to generate burn address is as follows:

                      Hash(G, "burningaddress", index)

    where ```G``` is base point of Edwards25519, ```index``` is the minimum positive integer number such that the last byte of output is zero. It will make sure that burn address is belong in Shard 0. ```Keccak256``` is used as the hash function.   

* The burn address at ```index = 68``` in ```base58encode``` is:
```15pGE5XZc7gsHSLgQxgZRVt7UsXBodiyTYe6xtvXipTFQPMpdQqtXhkzriL```

#### Reference
[1] https://github.com/incognitochain/incognito-chain/blob/master/utility/generateburnaddress.go
